name: Cypress Tests

on:
  push:
    branches:
      - master

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests

      - name: Install Dependencies XYZ
        run: npm install


      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm run moj:super:skrypt:xyz